name: "servstatusbot"
token: "6093475503:AAGUSBpvjMJkAKKz1f66xy1s6nyImPBxB50"

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/UrlDB
    username: postgres
    password: 555555

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect